name: Pipeline

on:
  push:
  workflow_dispatch:

jobs:

  Params:
    uses: pyTooling/Actions/.github/workflows/Parameters.yml@r0
    with:
      name: pyEDAA.CLITool

#  UnitTesting:
#    uses: pyTooling/Actions/.github/workflows/UnitTesting.yml@r0
#    needs:
#      - Params
#    with:
#      jobs: ${{ needs.Params.outputs.python_jobs }}
#      artifact: ${{ fromJson(needs.Params.outputs.params).artifacts.unittesting }}

#  Coverage:
#    uses: pyTooling/Actions/.github/workflows/CoverageCollection.yml@r0
#    needs:
#      - Params
#    with:
#      python_version: ${{ fromJson(needs.Params.outputs.params).python_version }}
#      artifact: ${{ fromJson(needs.Params.outputs.params).artifacts.coverage }}
#    secrets:
#      codacy_token: ${{ secrets.CODACY_PROJECT_TOKEN }}

#  PublishTestResults:
#    uses: pyTooling/Actions/.github/workflows/PublishTestResults.yml@r0
#    needs:
#      - UnitTesting

  Package:
    uses: pyTooling/Actions/.github/workflows/Package.yml@r0
    needs:
      - Params
      #- Coverage
    with:
      python_version: ${{ fromJson(needs.Params.outputs.params).python_version }}
      artifact: ${{ fromJson(needs.Params.outputs.params).artifacts.package }}

  Release:
    uses: pyTooling/Actions/.github/workflows/Release.yml@r0
    if: startsWith(github.ref, 'refs/tags')
    needs:
      #- UnitTesting
      #- Coverage
      - Package

  PublishOnPyPI:
    uses: pyTooling/Actions/.github/workflows/PublishOnPyPI.yml@r0
    if: startsWith(github.ref, 'refs/tags')
    needs:
      - Params
      - Release
      - Package
    with:
      python_version: ${{ fromJson(needs.Params.outputs.params).python_version }}
      artifact: ${{ fromJson(needs.Params.outputs.params).artifacts.package }}
    secrets:
      PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}

  BuildTheDocs:
    uses: pyTooling/Actions/.github/workflows/BuildTheDocs.yml@r0
    needs:
      - Params
    with:
      artifact: ${{ fromJson(needs.Params.outputs.params).artifacts.doc }}

  PublishToGitHubPages:
    uses: pyTooling/Actions/.github/workflows/PublishToGitHubPages.yml@r0
    needs:
      - Params
      - BuildTheDocs
      #- Coverage
    with:
      doc: ${{ fromJson(needs.Params.outputs.params).artifacts.doc }}
      #coverage: ${{ fromJson(needs.Params.outputs.params).artifacts.coverage }}

  ArtifactCleanUp:
    uses: pyTooling/Actions/.github/workflows/ArtifactCleanUp.yml@r0
    needs:
      - Params
      #- UnitTesting
      #- PublishTestResults
      #- Coverage
      - BuildTheDocs
      - PublishToGitHubPages
    with:
      package: ${{ fromJson(needs.Params.outputs.params).artifacts.package }}
      remaining: |
        ${{ fromJson(needs.Params.outputs.params).artifacts.doc }}
#        ${{ fromJson(needs.Params.outputs.params).artifacts.unittesting }}-3.6
#        ${{ fromJson(needs.Params.outputs.params).artifacts.unittesting }}-3.7
#        ${{ fromJson(needs.Params.outputs.params).artifacts.unittesting }}-3.8
#        ${{ fromJson(needs.Params.outputs.params).artifacts.unittesting }}-3.9
#        ${{ fromJson(needs.Params.outputs.params).artifacts.unittesting }}-3.10
#        ${{ fromJson(needs.Params.outputs.params).artifacts.coverage }}
